period_tokens:
  - month
  - year
  - day
  - week

language_related:
  - "jQuery": "JS"

languages:
  - "A#"
  - "A+"
  - "A++"
  - "ABAP"
  - "ActionScript"
  - "Ada"
  - "ALGOL"
  - "Alice"
  - "Apex"
  - "APL"
  - "AppleScript"
  - "Arc"
  - "AspectJ"
  - "Assembly"
  - "ASM"
  - "ATS"
  - "AutoHotkey"
  - "AutoIt"
  - "AutoLISP"
  - "AWK"
  - "ASP"
  - "ASP.NET"
  - "AngularJS"
  - "B"
  - "Babbage"
  - "Bash"
  - "BASIC"
  - "bc"
  - "BCPL"
  - "Batch"
  - "Boo"
  - "C"
  - "C--"
  - "C++"
  - "C#"
  - "Caml"
  - "Chef"
  - "Clojure"
  - "COBOL"
  - "Cobra"
  - "CoffeeScript"
  - "ColdFusion"
  - "COMAL"
  - "csh"
  - "CUDA"
  - "Curl"
  - "Cython"
  - "D"
  - "Dart"
  - "Delphi"
  - "E"
  - "E#"
  - "ECMAScript"
  - "Eiffel"
  - "Elixir"
  - "Elm"
  - "Erlang"
  - "F"
  - "F#"
  - "Forth"
  - "Fortran"
  - "G"
  - "GML"
  - "Genie"
  - "Go"
  - "Go!"
  - "Groovy"
  - "HTML"
  - "HTML5"
  - "Hack"
  - "Haskell"
  - "Haxe"
  - "High Level Assembly"
  - "HLA"
  - "HLSL"
  - "Icon"
  - "Id"
  - "IDL"
  - "IPL"
  - "J"
  - "J#"
  - "J++"
  - "JADE"
  - "Java"
  - "JavaScript"
  - "JS"
  - "Julia"
  - "Jython"
  - "K"
  - "ksh"
  - "L"
  - "L# .NET"
  - "LaTeX"
  - "LINC"
  - "Lisp"
  - "Logo"
  - "LiveScript"
  - "Lua"
  - "make"
  - "Maple"
  - "MASM"
  - "Mathematica"
  - "MATLAB"
  - "Maxima"
  - "Mercury"
  - "Mathcad"
  - "NASM"
  - "Objective-C"
  - "Objective-J"
  - "OCaml"
  - "Octave"
  - "OpenCL"
  - "P#"
  - "Perl"
  - "PDL"
  - "PHP"
  - "Pico"
  - "PL-11"
  - "PL/0"
  - "PL/B"
  - "PL/C"
  - "PL/I"
  - "PL/M"
  - "PL/P"
  - "PL/SQL"
  - "PL360"
  - "PLANC"
  - "PLEX"
  - "PostScript"
  - "Processing"
  - "Processing.js"
  - "Prograph"
  - "Prolog"
  - "Python"
  - "QtScript"
  - "QPL"
  - "R"
  - "R++"
  - "Racket"
  - "Ruby"
  - "Rust"
  - "S-Lang"
  - "S-PLUS"
  - "SAS"
  - "SASL"
  - "SBL"
  - "Scala"
  - "Scheme"
  - "Scilab"
  - "Scratch"
  - "Script.NET"
  - "Sed"
  - "Simula"
  - "Simulink"
  - "Smalltalk"
  - "SML"
  - "Squeak"
  - "Swift"
  - "T"
  - "Tcl"
  - "TeX"
  - "TEX"
  - "TIE"
  - "Timber"
  - "Trac"
  - "T-SQL"
  - "Transcript"
  - "TXL"
  - "TypeScript"
  - "Turbo C++"
  - "Ubercode"
  - "UNITY"
  - "VB"
  - "VB.NET"
  - "Visual Basic"
  - "Visual Basic .NET"
  - "Visual J++"
  - "Visual J#"
  - "PowerShell"
  - "Wolfram Language"
  - "X++"
  - "X#"
  - "XSLT"
  - "Zsh"
